TagDictionaries = { 
         'bdsm': '性虐待',
         'multi-work series': None,
         'collar': '项圈',
         'dark skin': '深色皮肤',
         'anal': '肛门',
         'human pet': None,
         'mosaic censorship': None,
         'gag': '口塞',
         'catgirl': '猫粮',
         'bodysuit': '紧身衣',
         'leash': None,
         'incest': None,
         'bondage': '拘束',
         'latex': '乳胶',
         'urination': None,
         'kemonomimi': None,
         'lolicon': None,
         'sole female': None,
         'sole male': None,
         'tail plug': '尾巴插件',
         'sex toys': '性玩具',
         'sister': None,
         'nipple piercing': '乳环',
         'ahegao': None,
         'big breasts': None,
         'mind control': None,
         'group': None,
         'piercing': None,
         'x-ray': '透视/剖面图',
         'masked face': None,
         'inflation': None,
         'omorashi': None,
         'gloves': None,
         'schoolgirl uniform': None,
         'thigh high boots': None,
         'magical girl': None,
         'shibari': None,
         'females only': '只有女性',
         'artbook': None,
         'full color': '全彩',
         'pantyhose': None,
         'ponytail': None,
         'scat': None,
         'stockings': None,
         'big clit': None,
         'urethra insertion': None,
         'enema': None,
         'mermaid': None,
         'rape': None,
         'story arc': None,
         'tankoubon': None,
         'tutor': None,
         'snuff': None,
         'squirting': None,
         'yuri': '百合',
         'lactation': None,
         'fingering': None,
         'strap-on': None,
         'gender bender': None,
         'gyaru': None,
         'birth': None,
         'monster': None,
         'hairy armpits': None,
         'low shotacon': None,
         'unusual insertions': None,
         'goblin': None,
         'shotacon': None,
         'forniphilia': None,
         'unusual pupils': None,
         'nipple stimulation': None,
         'nipple fuck': None,
         'solo action': None,
         'nipple birth': None,
         'masturbation': None,
         'nakadashi': None,
         'clit stimulation': None,
         'big penis': None,
         'clit growth': None,
         'multiple orgasms': None,
         'petrification': None,
         'stomach deformation': None,
         'anal birth': None,
         'big nipples': None,
         'drugs': None,
         'large insertions': None,
         'bestiality': None,
         'defloration': None,
         'wolf': None,
         'pillory': None,
         'kissing': None,
         'very long hair': '超长发',
         'blindfold': None,
         'bride': None,
         'niece': None,
         'bbm': None,
         'anal intercourse': None,
         'netorare': None,
         'futanari': None,
         'focus anal': None,
         'dilf': None,
         'uncensored': None,
         'body modification': None,
         'dick growth': None,
         'corruption': None,
         'double penetration': None,
         'blowjob': None,
         'petplay': '宠物游戏',
         'beauty mark': None,
         'mind break': None,
         'glasses': None,
         'blackmail': None,
         'machine': None,
         'milking': None,
         'gaping': None,
         'paizuri': None,
         'bald': None,
         'mmf threesome': None,
         'bikini': None,
         'voyeurism': None,
         'cheating': None,
         'business suit': None,
         'double anal': None,
         'milf': None,
         'big ass': None,
         'tickling': None,
         'witch': None,
         'bunny girl': None,
         'fisting': None,
         'fox girl': None,
         'femdom': None,
         'crossdressing': None,
         'feminization': None,
         'males only': '只有男性',
         'small penis': None,
         'josou seme': None,
         'yaoi': None,
         'tomgirl': None,
         'chastity belt': '贞操带',
         'slave': None,
         'harness': None,
         'dog': None,
         'exhibitionism': None,
         'garter belt': None,
         'impregnation': None,
         'tribadism': None,
         'makeup': None,
         'old man': None,
         'fishnets': None,
         'hairy': None,
         'minigirl': None,
         'onahole': None,
         'incomplete': None,
         'tentacles': None,
         'orgasm denial': None,
         'rimjob': None,
         'small breasts': '贫乳',
         'ssbbm': None,
         'smell': None,
         'living clothes': '触手服',
         'breast expansion': None,
         'age regression': None,
         'age progression': None,
         'doll joints': None,
         'drill hair': None,
         'amputee': None,
         'vore': None,
         'coprophagia': None,
         'pegging': None,
         'large tattoo': None,
         'vomit': None,
         'bloomers': None,
         'ryona': None,
         'sole dickgirl': None,
         'spanking': None,
         'inseki': None,
         'extraneous ads': None,
         'crotch tattoo': None,
         'tail': None,
         'doujinshi': '同人志',
         'horns': None,
         'asphyxiation': None,
         'sweating': None,
         'huge breasts': '巨乳',
         'pregnant': None,
         'eggs': None,
         'chloroform': None,
         'huge penis': None,
         'insect': None,
         'electric shocks': None,
         'corset': None,
         'kunoichi': None,
         'anthology': None,
         'compilation': None,
         'twintails': None,
         'low bestiality': None,
         'deepthroat': None,
         'torture': None,
         'low scat': None,
         'wooden horse': None,
         'whip': None,
         'emotionless sex': None,
         'lingerie': None,
         'speculum': None,
         'clamp': None,
         'cervix penetration': None,
         'teacher': None,
         'widow': None,
         'mother': None,
         'sleeping': None,
         'blood': None,
         'fairy': None,
         'wings': None,
         'dickgirl on dickgirl': None,
         'dickgirls only': None,
         'swimsuit': None,
         'vacbed': None,
         'footjob': None,
         'cosplaying': None,
         'prostitution': None,
         'triple penetration': None,
         'slime boy': None,
         'metal armor': None,
         'gender morph': None,
         'gender change': None,
         'parasite': None,
         'cannibalism': None,
         'guro': None,
         'artistcg': None,
         'prolapse': None,
         'military': None,
         'hotpants': None,
         'maid': None,
         'nun': None,
         'nose hook': '鼻环',
         'tanlines': None,
         'elf': '精灵',
         'cheerleader': None,
         'demon girl': '恶魔少女',
         'waiter': None,
         'bisexual': None,
         'waitress': None,
         'harem': None,
         'ffm threesome': None,
         'no penetration': None,
         'chikan': None,
         'twins': None,
         'chinese dress': None,
         'male on dickgirl': None,
         'scar': None,
         'daughter': None,
         'big balls': None,
         'humiliation': None,
         'muscle': None,
         'minotaur': None,
         'horse boy': None,
         'shemale': None,
         'watermarked': None,
         'variant set': None,
         'stuck in wall': None,
         'imageset': None,
         'diaper': '尿布',
         'eye-covering bang': None,
         'full censorship': None,
         'farting': None,
         'body writing': None,
         'forced exposure': None,
         'eyemask': None,
         'miniguy': None,
         'school swimsuit': None,
         'zinkurou': None,
         'transformation': None,
         'tailjob': None,
         'tailphagia': None,
         'absorption': None,
         'tube': None,
         'oil': None,
         'slime': None,
         'tiara': None,
         'transparent clothing': None,
         'clown': None,
         'yandere': None,
         'sunglasses': None,
         'filming': None,
         'bukkake': None,
         'thick eyebrows': None,
         'vtuber': None,
         'table masturbation': None,
         'exposed clothing': None,
         'hair buns': None,
         'horse cock': None,
         'low lolicon': None,
         'facial hair': None,
         'butler': None,
         'cervix prolapse': None,
         'personality excretion': None,
         'all the way through': None,
         'condom': None,
         'schoolboy uniform': None,
         'wormhole': None,
         'public use': None,
         'vampire': None,
         'vaginal sticker': None,
         'pasties': None,
         'horse': None,
         'cunnilingus': None,
         'inverted nipples': None,
         'high heels': None,
         'mouth mask': None,
         'human cattle': None,
         'straitjacket': None,
         'oyakodon': None,
         'policewoman': None,
         'apron': None,
         'long tongue': '长舌',
         'anal prolapse': '脱肛',
         'leotard': None,
         'goudoushi': None,
         'replaced': None,
         'possession': None,
         'shimapan': None,
         'skinsuit': None,
         'cbt': None,
         'painted nails': None,
         'tomboy': None,
         'unusual teeth': None,
         'infantilism': None,
         'monster girl': None,
         'hidden sex': None,
         'scanmark': None,
         'tracksuit': None,
         'lab coat': None,
         'gymshorts': None,
         'shared senses': None,
         'bike shorts': None,
         'pubic stubble': None,
         'domination loss': None,
         'time stop': None,
         'virginity': None,
         'miko': None,
         'randoseru': None,
         'gothic lolita': None,
         'gokkun': None,
         'dickgirl on male': None,
         'mtf threesome': None,
         'body painting': None,
         'robot': None,
         'oppai loli': None,
         'genital piercing': None,
         'pig': None,
         'v.v panda': None,
         'shimaidon': None,
         'mesuiki': None,
         'ghost': None,
         'kimono': None,
         'clone': None,
         'selfcest': None,
         'facesitting': None,
         'armpit licking': None,
         'detached sleeves': None,
         'prostate massage': None,
         'soushuuhen': None,
         'swinging': None,
         'slime girl': None,
         'crown': None,
         'cum swap': None,
         'gasmask': None,
         'smalldom': None,
         'orc': '兽人',
         'pixie cut': None,
         'shadow rangers': None,
         'moral degeneration': None,
         'vaginal birth': None,
         'dismantling': None,
         'bodystocking': None,
         'saliva': None,
         'crying': None,
         'cumflation': None,
         'dougi': None,
         'phone sex': None,
         'out of order': None,
         'spider girl': None,
         'spider': None,
         'ponygirl': '小马女孩',
         'multiple paizuri': None,
         'eyepatch': None,
         'bbw': None,
         'manga': None,
         'assjob': None,
         'nurse': None,
         'wet clothes': '湿衣服',
         'clothed male nude female': None,
         'unbirth': None,
         'trampling': None,
         'multimouth blowjob': None,
         'mmm threesome': None,
         'anorexic': None,
         'breast feeding': None,
         'wolf girl': None,
         'alien girl': None,
         'double vaginal': None,
         'bunny boy': None,
         'big areolae': None,
         'piss drinking': None,
         'foot insertion': None,
         'fff threesome': None,
         'angel': None,
         'rough grammar': None,
         'comic': None,
         'stirrup legwear': None,
         'dog girl': None,
         'cowgirl': None,
         'webtoon': None,
         'stewardess': None,
         'blowjob face': None,
         'ttf threesome': None,
         'heterochromia': None,
         'brain fuck': None,
         'navel fuck': None,
         'policeman': None,
         'foot licking': None,
         'body swap': None,
         'ear fuck': None,
         'worm': None,
         'mirrorwu': None,
         'syringe': None,
         'nose fuck': None,
         'hairjob': None,
         'ttm threesome': None,
         'ball sucking': None,
         'frottage': None,
         'cock ring': None,
         'school gym uniform': None,
         'nudity only': None,
         'oni': None,
         'halo': None,
         'non-h': None,
         'misc': None,
         'harpy': None,
         'pole dancing': None,
         'eye penetration': None,
         'gigantic breasts': None,
         'mecha girl': None,
         'animegao': None,
         'animated': None,
         'freckles': None,
         'demon': None,
         'rabbit': None,
         'wrestling': None,
         'smegma': None,
         'widower': None,
         'autofellatio': None,
         'handjob': None,
         'glory hole': None,
         'zombie': None,
         'hanging': None,
         'balls expansion': None,
         'kappa': None,
         'multiple breasts': None,
         'octopus': None,
         'phimosis': None,
         'fish': None,
         'alien': None,
         'pig girl': None,
         'closed eyes': None,
         'insect girl': None,
         'centaur': None,
         'cousin': None,
         'multipanel sequence': None,
         'triple anal': None,
         'smoking': None,
         'scat insertion': None,
         'tall man': None,
         'tights': None,
         'analphagia': None,
         'clothed paizuri': None,
         'focus blowjob': None,
         'monkey': None,
         'bull': None,
         'father': None,
         'how to': None,
         'atsuko hakari': None,
         'underwater': None,
         'multiple penises': None,
         'maggot': None,
         'already uploaded': None,
         'aunt': None,
         'plant girl': None,
         'slug': None,
         'drunk': None,
         'granddaughter': None,
         'moriyama inu': None,
}